[package]
name = "ppr"
version = "0.1.0"
authors = ["Marc <vengeurk@gmail.com>"]

[dependencies]
bytes = "0.4.5"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
futures = "0.1.16"

[lib]
name = "reactive_rs"
path = "src/lib.rs"